### PR TITLE
A2 hash should use the request's method (closes #13)

### LINKED ISSUE #13: client.Changes.SetReview fails with 401 Unauthorized
For the installation of Gerrit I'm using, the following code fails:

```go
package main

import (
	"fmt"
	"github.com/andygrunwald/go-gerrit"
)

func main()  {
	client, err := gerrit.NewClient("<server>", nil)
	if err != nil {
		panic(err)
	}

	username := "<username>"
	password := "<password>"
	client.Authentication.SetDigestAuth(username, password)

	input := &gerrit.ReviewInput{
		Message: "FOOBAR",
		Drafts: "PUBLISH_ALL_REVISIONS",
	}
	info, response, err := client.Changes.SetReview(
		"<change-id>",
		"<revision>",
		input,
	)
	if err != nil {
		fmt.Println(response)
		fmt.Println(err)
	}
}

```

With this output:
```
API call to <server>/a/<change-id>/revisions/<revision>/review failed: 401 Unauthorized
```

Interestingly, it works using cURL:
```
curl -XPOST -v <server>/a/changes/<change-id>/revisions/<revision>/review' -H 'Content-Type: application/json' --data '{"drafts":"PUBLISH_ALL_REVISIONS","message":"FOOBAR"}' --digest -u <username>:<password>
```

And produces (content modified to show general request flow)
```
> POST /a/changes/<change-id>/revisions/<revision>/review HTTP/1.1
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 0
>
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Digest [ redacted ]
> POST /a/changes/<change-id>/revisions/<revision>/review HTTP/1.1
> Authorization: Digest [redacted]
> Accept: */*
> Content-Type: application/json
> Content-Length: 52
>
* upload completely sent off: 52 out of 52 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 8
<
)]}'
{}
```

For some reason, `/review` seems to handle the contents of the request a little differently.  I'm still trying to figure out why exactly.  At first `/review` was returning a broken response but that turned out to be because we're reusing the request body for digest auth.  With that being fixed by #12, I'm opening this issue to track the fix for `/review`.

### PR DESCRIPTION
**Pull request by opalmer**
According to RFC2617 3.2.2.3 A2, 'If the "qop" directive's
value is "auth" or is unspecified, then A2 is':
```
  A2       = Method ":" digest-uri-value
```
Before this commit 'Method' was always GET even if
the request was a POST, PUT, etc.

For some reason, this bug has only posed a problem
for SetReview.  In other cases Gerrit seems to accept
the request rather than returning 401 Unauthorized.

### CODE REVIEW

**Comment by opalmer** [comment]
@andygrunwald PTAL.

Also, thanks @timou for the second set of eyes when debugging this!

File: authentication.go [hunk 1]
```diff
@@ -51,7 +51,7 @@ func (s *AuthenticationService) SetDigestAuth(username, password string) {
 // returns 401 Unauthorized and authType was set to authTypeDigest. The
 // resulting string is used to set the Authorization header before retrying
 // the request.
-func (s *AuthenticationService) digestAuthHeader(response *http.Response) (string, error) {
+func (s *AuthenticationService) digestAuthHeader(method string, response *http.Response) (string, error) {
```
Comment (andygrunwald) [inline authentication.go]: The `response` object contains the original request.
So you don`t have to pass the `method` here.
I think `response.Request.Method` should work here.
See https://golang.org/pkg/net/http/#Response

What do you think?

**Comment by andygrunwald** [comment]
Thank you for debugging this. I made one small commit and like to get your feedback.
Otherwise, fine :) Feel free to merge it.

File: authentication.go (hunk 1 above)
Comment (opalmer) [inline authentication.go]: Agreed and good point.  We're already using `response.Reques`t elsewhere in that same function too...not sure why I missed it.
